import 'controller/apply_job_type_of_work_controller.dart';import 'package:final_project/core/app_export.dart';import 'package:final_project/widgets/app_bar/appbar_leading_image.dart';import 'package:final_project/widgets/app_bar/appbar_subtitle.dart';import 'package:final_project/widgets/app_bar/custom_app_bar.dart';import 'package:final_project/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class ApplyJobTypeOfWorkScreen extends GetWidget<ApplyJobTypeOfWorkController> {const ApplyJobTypeOfWorkScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 17.v), child: Column(children: [_buildStep(), SizedBox(height: 34.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_type_of_work".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 5.v), Align(alignment: Alignment.centerLeft, child: Text("msg_fill_in_your_bio".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 28.v), _buildSeniorUXDesigner(), SizedBox(height: 16.v), _buildSeniorUIDesigner(), SizedBox(height: 16.v), _buildGraphikDesigner(), SizedBox(height: 16.v), _buildFrontEndDeveloper(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildNext())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_apply_job".tr)); } 
/// Section Widget
Widget _buildStep() { return Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 22.h, right: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Column(children: [CustomImageView(imagePath: ImageConstant.imgVuesaxBoldTickCircle, height: 44.adaptSize, width: 44.adaptSize), SizedBox(height: 9.v), Text("lbl_biodata".tr, style: theme.textTheme.bodySmall)]), Padding(padding: EdgeInsets.only(top: 35.v, bottom: 33.v), child: SizedBox(width: 49.h, child: Divider(color: theme.colorScheme.primary, indent: 25.h))), Padding(padding: EdgeInsets.only(left: 14.h), child: Column(children: [Container(width: 44.adaptSize, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 11.v), decoration: AppDecoration.outlinePrimary3.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("lbl_2".tr, style: CustomTextStyles.titleMediumPrimary)), SizedBox(height: 10.v), Text("lbl_type_of_work".tr, style: theme.textTheme.bodySmall)])), Padding(padding: EdgeInsets.only(top: 35.v, bottom: 33.v), child: SizedBox(width: 38.h, child: Divider(color: appTheme.blueGray100, indent: 14.h))), Padding(padding: EdgeInsets.only(left: 6.h), child: Column(children: [Container(width: 44.adaptSize, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 11.v), decoration: AppDecoration.outlineBluegray300.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("lbl_3".tr, style: CustomTextStyles.titleMediumBluegray300)), SizedBox(height: 10.v), Text("msg_upload_portfolio".tr, style: CustomTextStyles.bodySmallPrimaryContainer)]))]))); } 
/// Section Widget
Widget _buildSeniorUXDesigner() { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Column(children: [Text("msg_senior_ux_designer".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), SizedBox(width: 139.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_cv_pdf".tr, style: theme.textTheme.titleSmall), Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 7.v), decoration: BoxDecoration(color: appTheme.blueGray200, borderRadius: BorderRadius.circular(2.h))), Text("lbl_portfolio_pdf".tr, style: theme.textTheme.titleSmall)]))])), CustomImageView(imagePath: ImageConstant.imgIconBlueGray200, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 12.v))])); } 
/// Section Widget
Widget _buildSeniorUIDesigner() { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_senior_ui_designer".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), SizedBox(width: 139.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_cv_pdf".tr, style: theme.textTheme.titleSmall), Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 7.v), decoration: BoxDecoration(color: appTheme.blueGray200, borderRadius: BorderRadius.circular(2.h))), Text("lbl_portfolio_pdf".tr, style: theme.textTheme.titleSmall)]))])), CustomImageView(imagePath: ImageConstant.imgIcon, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 12.v))])); } 
/// Section Widget
Widget _buildGraphikDesigner() { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_graphik_designer".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), SizedBox(width: 139.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_cv_pdf".tr, style: theme.textTheme.titleSmall), Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 7.v), decoration: BoxDecoration(color: appTheme.blueGray200, borderRadius: BorderRadius.circular(2.h))), Text("lbl_portfolio_pdf".tr, style: theme.textTheme.titleSmall)]))])), CustomImageView(imagePath: ImageConstant.imgIconBlueGray200, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 12.v))])); } 
/// Section Widget
Widget _buildFrontEndDeveloper() { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_front_end_developer".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), Row(children: [Text("lbl_cv_pdf".tr, style: theme.textTheme.titleSmall), Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.only(left: 8.h, top: 5.v, bottom: 7.v), decoration: BoxDecoration(color: appTheme.blueGray200, borderRadius: BorderRadius.circular(2.h))), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_portfolio_pdf".tr, style: theme.textTheme.titleSmall))])])), CustomImageView(imagePath: ImageConstant.imgIconBlueGray200, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 12.v))])); } 
/// Section Widget
Widget _buildNext() { return CustomElevatedButton(text: "lbl_next".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 40.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
