import '../job_detail_description_tab_container_screen/widgets/category12_item_widget.dart';import 'controller/job_detail_description_tab_container_controller.dart';import 'models/category12_item_model.dart';import 'package:final_project/core/app_export.dart';import 'package:final_project/presentation/job_detail_description_page/job_detail_description_page.dart';import 'package:final_project/widgets/app_bar/appbar_leading_image.dart';import 'package:final_project/widgets/app_bar/appbar_subtitle.dart';import 'package:final_project/widgets/app_bar/appbar_trailing_image.dart';import 'package:final_project/widgets/app_bar/custom_app_bar.dart';import 'package:final_project/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';class JobDetailDescriptionTabContainerScreen extends GetWidget<JobDetailDescriptionTabContainerController> {const JobDetailDescriptionTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 32.v), CustomIconButton(height: 48.adaptSize, width: 48.adaptSize, padding: EdgeInsets.all(9.h), child: CustomImageView(imagePath: ImageConstant.imgTwitterWhiteA700)), SizedBox(height: 13.v), Text("msg_senior_ui_designer".tr, style: theme.textTheme.titleLarge), SizedBox(height: 4.v), Text("msg_twitter_jakarta".tr, style: CustomTextStyles.bodySmallBluegray800), SizedBox(height: 16.v), _buildCategory(), SizedBox(height: 32.v), _buildTabview(), SizedBox(height: 470.v, child: TabBarView(controller: controller.tabviewController, children: [JobDetailDescriptionPage(), JobDetailDescriptionPage(), JobDetailDescriptionPage()]))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 40.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_job_detail".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgBookmarkPrimary, margin: EdgeInsets.symmetric(horizontal: 24.h))]); } 
/// Section Widget
Widget _buildCategory() { return Obx(() => Wrap(runSpacing: 8.v, spacing: 8.h, children: List<Widget>.generate(controller.jobDetailDescriptionTabContainerModelObj.value.category12ItemList.value.length, (index) {Category12ItemModel model = controller.jobDetailDescriptionTabContainerModelObj.value.category12ItemList.value[index]; return Category12ItemWidget(model);}))); } 
/// Section Widget
Widget _buildTabview() { return Container(height: 46.v, width: 327.h, decoration: BoxDecoration(color: appTheme.gray100, borderRadius: BorderRadius.circular(23.h)), child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.whiteA700, labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'SF Pro Display', fontWeight: FontWeight.w500), unselectedLabelColor: appTheme.gray60001, unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'SF Pro Display', fontWeight: FontWeight.w500), indicatorPadding: EdgeInsets.all(3.0.h), indicator: BoxDecoration(color: appTheme.indigo90001, borderRadius: BorderRadius.circular(20.h)), tabs: [Tab(child: Text("lbl_desicription".tr)), Tab(child: Text("lbl_company".tr)), Tab(child: Text("lbl_people".tr))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
