import 'controller/apply_job_upload_portfolio_one_controller.dart';import 'package:dotted_border/dotted_border.dart';import 'package:final_project/core/app_export.dart';import 'package:final_project/widgets/app_bar/appbar_leading_image.dart';import 'package:final_project/widgets/app_bar/appbar_subtitle.dart';import 'package:final_project/widgets/app_bar/custom_app_bar.dart';import 'package:final_project/widgets/custom_elevated_button.dart';import 'package:final_project/widgets/custom_icon_button.dart';import 'package:final_project/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';class ApplyJobUploadPortfolioOneScreen extends GetWidget<ApplyJobUploadPortfolioOneController> {const ApplyJobUploadPortfolioOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 17.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildFrame(), SizedBox(height: 34.v), Text("msg_upload_portfolio".tr, style: theme.textTheme.titleLarge), SizedBox(height: 5.v), Text("msg_fill_in_your_bio".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 29.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_upload_cv2".tr, style: theme.textTheme.titleMedium), TextSpan(text: "lbl".tr, style: CustomTextStyles.titleMediumRed50001)]), textAlign: TextAlign.left), SizedBox(height: 11.v), _buildInput(), SizedBox(height: 20.v), Text("lbl_other_file".tr, style: theme.textTheme.titleMedium), SizedBox(height: 12.v), _buildUploadDocument(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildSubmit())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_apply_job".tr)); } 
/// Section Widget
Widget _buildFrame() { return Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 22.h, right: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Column(children: [CustomImageView(imagePath: ImageConstant.imgVuesaxBoldTickCircle, height: 44.adaptSize, width: 44.adaptSize), SizedBox(height: 9.v), Text("lbl_biodata".tr, style: theme.textTheme.bodySmall)]), Padding(padding: EdgeInsets.only(top: 35.v, bottom: 33.v), child: SizedBox(width: 49.h, child: Divider(color: theme.colorScheme.primary, indent: 25.h))), Padding(padding: EdgeInsets.only(left: 14.h), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgVuesaxBoldTickCircle, height: 44.adaptSize, width: 44.adaptSize), SizedBox(height: 10.v), Text("lbl_type_of_work".tr, style: theme.textTheme.bodySmall)])), Padding(padding: EdgeInsets.only(top: 35.v, bottom: 33.v), child: SizedBox(width: 38.h, child: Divider(color: theme.colorScheme.primary, indent: 14.h))), Padding(padding: EdgeInsets.only(left: 6.h), child: Column(children: [Container(width: 44.adaptSize, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 11.v), decoration: AppDecoration.outlinePrimary3.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("lbl_3".tr, style: CustomTextStyles.titleMediumPrimary)), SizedBox(height: 10.v), Text("msg_upload_portfolio".tr, style: theme.textTheme.bodySmall)]))]))); } 
/// Section Widget
Widget _buildInput() { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgLogo, height: 40.adaptSize, width: 40.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_rafif_dian_cv".tr, style: CustomTextStyles.titleSmallPrimaryContainer), SizedBox(height: 7.v), Text("lbl_cv_pdf_300kb".tr, style: CustomTextStyles.bodySmallGray60001)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgEdit, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 8.v)), CustomImageView(imagePath: ImageConstant.imgClose, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 8.v))])); } 
/// Section Widget
Widget _buildUploadDocument() { return DottedBorder(color: theme.colorScheme.onPrimaryContainer, padding: EdgeInsets.only(left: 1.h, top: 1.v, right: 1.h, bottom: 1.v), strokeWidth: 1.h, radius: Radius.circular(8), borderType: BorderType.RRect, dashPattern: [5, 5], child: Container(padding: EdgeInsets.all(14.h), decoration: AppDecoration.outlineOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 56.adaptSize, width: 56.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillBlue, child: CustomImageView(imagePath: ImageConstant.imgVuesaxBoldDocumentUpload)), SizedBox(height: 18.v), Text("msg_upload_your_other".tr, style: CustomTextStyles.titleMedium18), SizedBox(height: 7.v), Text("msg_max_file_size_10".tr, style: CustomTextStyles.bodySmallGray60001), SizedBox(height: 25.v), CustomOutlinedButton(height: 40.v, text: "lbl_add_file".tr, leftIcon: Container(margin: EdgeInsets.only(right: 10.h), child: CustomImageView(imagePath: ImageConstant.imgUpload, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.outlinePrimary, buttonTextStyle: CustomTextStyles.titleMediumPrimary), SizedBox(height: 4.v)]))); } 
/// Section Widget
Widget _buildSubmit() { return CustomElevatedButton(text: "lbl_submit".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 40.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
