import 'controller/education_controller.dart';import 'package:final_project/core/app_export.dart';import 'package:final_project/widgets/app_bar/appbar_leading_image.dart';import 'package:final_project/widgets/app_bar/appbar_subtitle.dart';import 'package:final_project/widgets/app_bar/custom_app_bar.dart';import 'package:final_project/widgets/custom_elevated_button.dart';import 'package:final_project/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class EducationScreen extends GetWidget<EducationController> {const EducationScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 32.v), child: Column(children: [Container(margin: EdgeInsets.symmetric(horizontal: 2.h), padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 12.v), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_university".tr, style: CustomTextStyles.titleMediumBluegray300)), SizedBox(height: 5.v), CustomTextFormField(controller: controller.frameController, hintText: "msg_northern_michigan".tr, hintStyle: CustomTextStyles.titleMediumBluegray90001, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 17.v)), SizedBox(height: 16.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_title".tr, style: CustomTextStyles.titleMediumBluegray300)), SizedBox(height: 6.v), CustomTextFormField(controller: controller.bachelorController, hintText: "lbl_bachelor".tr, hintStyle: CustomTextStyles.titleMediumBluegray90001, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 17.v)), SizedBox(height: 16.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_start_year".tr, style: CustomTextStyles.titleMediumBluegray300)), SizedBox(height: 6.v), _buildForm(month: "lbl_december_2019".tr), SizedBox(height: 16.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_end_year".tr, style: CustomTextStyles.titleMediumBluegray300)), SizedBox(height: 6.v), _buildForm(month: "lbl_december_2022".tr), SizedBox(height: 32.v), CustomElevatedButton(height: 42.v, text: "lbl_save".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL21, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700), SizedBox(height: 2.v)])), SizedBox(height: 24.v), _buildEducationRow(), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 40.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_education".tr)); } 
/// Section Widget
Widget _buildEducationRow() { return Container(margin: EdgeInsets.only(right: 2.h), padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 15.v), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgLogo44x44, height: 44.adaptSize, width: 44.adaptSize, radius: BorderRadius.circular(22.h), margin: EdgeInsets.symmetric(vertical: 11.v)), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h, top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_the_university_of".tr, style: theme.textTheme.titleMedium), SizedBox(height: 6.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_bachelor_of_art".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 3.v), Text("lbl_2012_2015".tr, style: CustomTextStyles.bodyMediumBluegray300_1)])), CustomImageView(imagePath: ImageConstant.imgEdit, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 15.v))])])))])); } 
/// Common widget
Widget _buildForm({required String month}) { return Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 16.v), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v, bottom: 2.v), child: Text(month, style: CustomTextStyles.titleMediumBluegray90001.copyWith(color: appTheme.blueGray90001))), CustomImageView(imagePath: ImageConstant.imgCalendar, height: 24.adaptSize, width: 24.adaptSize)])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
