import 'controller/apply_job_biodata_controller.dart';import 'package:final_project/core/app_export.dart';import 'package:final_project/core/utils/validation_functions.dart';import 'package:final_project/widgets/app_bar/appbar_leading_image.dart';import 'package:final_project/widgets/app_bar/appbar_subtitle.dart';import 'package:final_project/widgets/app_bar/custom_app_bar.dart';import 'package:final_project/widgets/custom_elevated_button.dart';import 'package:final_project/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class ApplyJobBiodataScreen extends GetWidget<ApplyJobBiodataController> {ApplyJobBiodataScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 17.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildStep(), SizedBox(height: 32.v), Text("lbl_biodata".tr, style: theme.textTheme.titleLarge), SizedBox(height: 6.v), Text("msg_fill_in_your_bio".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 28.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_full_name2".tr, style: theme.textTheme.bodyLarge), TextSpan(text: "lbl".tr, style: CustomTextStyles.bodyLargeRed50001)]), textAlign: TextAlign.left), SizedBox(height: 8.v), _buildFullName(), SizedBox(height: 20.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_email".tr, style: theme.textTheme.bodyLarge), TextSpan(text: "lbl".tr, style: CustomTextStyles.bodyLargeRed50001)]), textAlign: TextAlign.left), SizedBox(height: 8.v), _buildEmail(), SizedBox(height: 21.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_no_handphone".tr, style: theme.textTheme.bodyLarge), TextSpan(text: "lbl".tr, style: CustomTextStyles.bodyLargeRed50001)]), textAlign: TextAlign.left), SizedBox(height: 7.v), _buildPhone(), SizedBox(height: 5.v)]))), bottomNavigationBar: _buildNext())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_apply_job".tr)); } 
/// Section Widget
Widget _buildStep() { return Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 22.h, right: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Column(children: [CustomImageView(imagePath: ImageConstant.imgVuesaxBoldTickCircle, height: 44.adaptSize, width: 44.adaptSize), SizedBox(height: 9.v), Text("lbl_biodata".tr, style: theme.textTheme.bodySmall)]), Padding(padding: EdgeInsets.only(top: 35.v, bottom: 33.v), child: SizedBox(width: 49.h, child: Divider(color: appTheme.blueGray100, indent: 25.h))), Padding(padding: EdgeInsets.only(left: 14.h), child: Column(children: [Container(width: 44.adaptSize, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 11.v), decoration: AppDecoration.outlineBluegray300.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("lbl_2".tr, style: CustomTextStyles.titleMediumBluegray300)), SizedBox(height: 10.v), Text("lbl_type_of_work".tr, style: CustomTextStyles.bodySmallPrimaryContainer)])), Padding(padding: EdgeInsets.only(top: 35.v, bottom: 33.v), child: SizedBox(width: 38.h, child: Divider(color: appTheme.blueGray100, indent: 14.h))), Padding(padding: EdgeInsets.only(left: 6.h), child: Column(children: [Container(width: 44.adaptSize, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 11.v), decoration: AppDecoration.outlineBluegray300.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("lbl_3".tr, style: CustomTextStyles.titleMediumBluegray300)), SizedBox(height: 10.v), Text("msg_upload_portfolio".tr, style: CustomTextStyles.bodySmallPrimaryContainer)]))]))); } 
/// Section Widget
Widget _buildFullName() { return CustomTextFormField(controller: controller.fullNameController, hintText: "msg_rafif_dian_axelingga".tr, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 18.v, 12.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgUserBlueGray30020x20, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v)); } 
/// Section Widget
Widget _buildEmail() { return CustomTextFormField(controller: controller.emailController, hintText: "msg_rafifdian12_gmail_com".tr, textInputType: TextInputType.emailAddress, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 18.v, 12.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgSms, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}); } 
/// Section Widget
Widget _buildPhone() { return CustomTextFormField(controller: controller.phoneController, hintText: "lbl_0100_666_7234".tr, textInputAction: TextInputAction.done, prefix: Padding(padding: EdgeInsets.fromLTRB(16.h, 19.v, 30.h, 19.v), child: Row(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imageNotFound, height: 18.v, width: 24.h, radius: BorderRadius.circular(2.h)), CustomImageView(imagePath: ImageConstant.imageNotFound, height: 16.v, width: 15.66.h, margin: EdgeInsets.symmetric(horizontal: 30.h, vertical: 20.v))])), prefixConstraints: BoxConstraints(maxHeight: 56.v), borderDecoration: TextFormFieldStyleHelper.outlineBlueGrayTL81, filled: false); } 
/// Section Widget
Widget _buildNext() { return CustomElevatedButton(text: "lbl_next".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 40.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
