import 'controller/experience_controller.dart';import 'package:final_project/core/app_export.dart';import 'package:final_project/widgets/app_bar/appbar_leading_image.dart';import 'package:final_project/widgets/app_bar/appbar_subtitle.dart';import 'package:final_project/widgets/app_bar/custom_app_bar.dart';import 'package:final_project/widgets/custom_drop_down.dart';import 'package:final_project/widgets/custom_elevated_button.dart';import 'package:final_project/widgets/custom_icon_button.dart';import 'package:final_project/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class ExperienceScreen extends GetWidget<ExperienceController> {const ExperienceScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 15.v), child: Padding(padding: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 5.v), child: Column(children: [Container(margin: EdgeInsets.only(left: 2.h), padding: EdgeInsets.all(11.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_position".tr, style: CustomTextStyles.titleMediumBluegray300), SizedBox(height: 6.v), _buildProductDesigner(), SizedBox(height: 17.v), Text("lbl_type_of_work".tr, style: CustomTextStyles.titleMediumBluegray300), SizedBox(height: 5.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 17.v, 12.h, 17.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray90002, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_full_time2".tr, items: controller.experienceModelObj.value.dropdownItemList!.value, contentPadding: EdgeInsets.only(left: 12.h, top: 17.v, bottom: 17.v), onChanged: (value) {controller.onSelected(value);}), SizedBox(height: 17.v), Text("lbl_company_name".tr, style: CustomTextStyles.titleMediumBluegray300), SizedBox(height: 5.v), _buildName(), SizedBox(height: 16.v), Text("lbl_location".tr, style: CustomTextStyles.titleMediumBluegray300), SizedBox(height: 6.v), _buildLocation(), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(right: 69.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgClosePrimary, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 4.v, bottom: 2.v), child: Text("msg_i_am_currently_working".tr, style: CustomTextStyles.titleSmallPrimaryContainer))])), SizedBox(height: 16.v), Text("lbl_start_year2".tr, style: CustomTextStyles.titleMediumBluegray300), SizedBox(height: 6.v), _buildFebruaryCounter(), SizedBox(height: 32.v), _buildSave(), SizedBox(height: 3.v)])), SizedBox(height: 24.v), _buildExperience()])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_experience".tr)); } 
/// Section Widget
Widget _buildProductDesigner() { return CustomTextFormField(controller: controller.productDesignerController, hintText: "msg_product_designer".tr, hintStyle: CustomTextStyles.titleMediumBluegray90001, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 17.v)); } 
/// Section Widget
Widget _buildName() { return CustomTextFormField(controller: controller.nameController, hintText: "lbl_supafast_studio".tr, hintStyle: CustomTextStyles.titleMediumBluegray90001, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 17.v)); } 
/// Section Widget
Widget _buildLocation() { return CustomTextFormField(controller: controller.locationController, hintText: "msg_purwokerto_banyumas".tr, hintStyle: CustomTextStyles.titleMediumBluegray90001, prefix: Container(margin: EdgeInsets.symmetric(horizontal: 12.h, vertical: 17.v), child: CustomImageView(imagePath: ImageConstant.imgLocationPrimarycontainer, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 55.v)); } 
/// Section Widget
Widget _buildFebruaryCounter() { return CustomTextFormField(controller: controller.februaryCounterController, hintText: "lbl_february_2021".tr, hintStyle: CustomTextStyles.titleMediumBluegray90001, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 17.v)); } 
/// Section Widget
Widget _buildSave() { return CustomElevatedButton(height: 42.v, text: "lbl_save".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL21, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700); } 
/// Section Widget
Widget _buildExperience() { return Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 15.v), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.symmetric(vertical: 11.v), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(7.h), decoration: IconButtonStyleHelper.fillBlueTL221, child: CustomImageView(imagePath: ImageConstant.imgLogoWhiteA700))), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h, top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_senior_ui_ux_designer".tr, style: theme.textTheme.titleMedium), SizedBox(height: 5.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_remote_growup".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 3.v), Text("lbl_2019_2022".tr, style: CustomTextStyles.bodyMediumBluegray300_1)])), CustomImageView(imagePath: ImageConstant.imgEdit, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 15.v))])])))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
