import 'controller/create_account_five_controller.dart';import 'package:final_project/core/app_export.dart';import 'package:final_project/widgets/app_bar/appbar_leading_image.dart';import 'package:final_project/widgets/app_bar/appbar_subtitle_two.dart';import 'package:final_project/widgets/app_bar/appbar_trailing_image.dart';import 'package:final_project/widgets/app_bar/custom_app_bar.dart';import 'package:final_project/widgets/custom_elevated_button.dart';import 'package:final_project/widgets/custom_outlined_button.dart';import 'package:final_project/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class CreateAccountFiveScreen extends GetWidget<CreateAccountFiveController> {const CreateAccountFiveScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 23.v), child: Column(children: [SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_cereate_account".tr, style: theme.textTheme.headlineMedium)), SizedBox(height: 12.v), Text("msg_please_create_an".tr, style: CustomTextStyles.bodyLargeGray60001), SizedBox(height: 43.v), _buildInputOne(), SizedBox(height: 16.v), _buildInputTwo(), SizedBox(height: 16.v), _buildPasswordInput(), SizedBox(height: 12.v), Align(alignment: Alignment.centerLeft, child: Text("msg_password_must_be".tr, style: CustomTextStyles.bodyLargeRed50001_1)), Spacer(), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_already_have_an".tr, style: CustomTextStyles.titleSmallBluegray300), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_login".tr, style: CustomTextStyles.titleSmallPrimary))]), SizedBox(height: 24.v), _buildCreateAccountButton(), SizedBox(height: 20.v), _buildOrRow()])), bottomNavigationBar: _buildButton())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 24.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h), onTap: () {onTapArrowLeft();}), actions: [Container(height: 20.000004.v, width: 81.h, margin: EdgeInsets.fromLTRB(24.h, 2.v, 24.h, 1.v), child: Stack(alignment: Alignment.topLeft, children: [AppbarSubtitleTwo(text: "lbl_j_bsque".tr), AppbarTrailingImage(imagePath: ImageConstant.imgSearchPrimary14x14, margin: EdgeInsets.fromLTRB(10.h, 2.v, 57.h, 3.v))]))]); } 
/// Section Widget
Widget _buildInputOne() { return CustomTextFormField(controller: controller.inputOneController, hintText: "lbl_rafif_dian_ax".tr, hintStyle: CustomTextStyles.titleSmallPrimary_1, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 18.v, 12.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgUserBlueGray90002, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v)); } 
/// Section Widget
Widget _buildInputTwo() { return CustomTextFormField(controller: controller.inputTwoController, hintText: "msg_rafifdian12_gma".tr, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 18.v, 12.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgSms, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v)); } 
/// Section Widget
Widget _buildPasswordInput() { return Obx(() => CustomTextFormField(controller: controller.passwordInputController, textInputAction: TextInputAction.done, prefix: Padding(padding: EdgeInsets.fromLTRB(16.h, 18.v, 30.h, 18.v), child: Row(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imageNotFound, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.fromLTRB(16.h, 18.v, 30.h, 18.v)), CustomImageView(imagePath: ImageConstant.imageNotFound, height: 15.v, width: 48.h)])), prefixConstraints: BoxConstraints(maxHeight: 56.v), suffix: InkWell(onTap: () {controller.isShowPassword.value = !controller.isShowPassword.value;}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 16.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgCloseBlueGray90002, height: 20.adaptSize, width: 20.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 56.v), obscureText: controller.isShowPassword.value)); } 
/// Section Widget
Widget _buildCreateAccountButton() { return CustomElevatedButton(text: "lbl_create_account".tr); } 
/// Section Widget
Widget _buildOrRow() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 7.v, bottom: 8.v), child: SizedBox(width: 64.h, child: Divider(color: appTheme.blueGray100))), Text("msg_or_sign_up_with".tr, style: theme.textTheme.bodyMedium), Padding(padding: EdgeInsets.only(top: 7.v, bottom: 8.v), child: SizedBox(width: 64.h, child: Divider(color: appTheme.blueGray100)))]); } 
/// Section Widget
Widget _buildGoogleButton() { return CustomOutlinedButton(width: 154.h, text: "lbl_google".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgFullcolorsGoogle, height: 16.adaptSize, width: 16.adaptSize))); } 
/// Section Widget
Widget _buildFacebookButton() { return CustomOutlinedButton(width: 154.h, text: "lbl_facebook".tr, margin: EdgeInsets.only(left: 19.h), leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgFacebook, height: 20.adaptSize, width: 20.adaptSize))); } 
/// Section Widget
Widget _buildButton() { return Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 40.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildGoogleButton(), _buildFacebookButton()])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
