import 'controller/terms_conditions_controller.dart';import 'package:final_project/core/app_export.dart';import 'package:final_project/widgets/app_bar/appbar_leading_image.dart';import 'package:final_project/widgets/app_bar/appbar_subtitle.dart';import 'package:final_project/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class TermsConditionsScreen extends GetWidget<TermsConditionsController> {const TermsConditionsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 5.v), child: Column(children: [SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Text("msg_your_privacy_is".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 11.v), SizedBox(width: 327.h, child: Text("msg_lorem_ipsum_dolor4".tr, maxLines: 11, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumBluegray500.copyWith(height: 1.40))), SizedBox(height: 15.v), SizedBox(width: 323.h, child: Text("msg_nam_vel_augue_sit".tr, maxLines: 6, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumBluegray500.copyWith(height: 1.40))), SizedBox(height: 23.v), Align(alignment: Alignment.centerLeft, child: Container(width: 254.h, margin: EdgeInsets.only(right: 72.h), child: Text("msg_data_controllers".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleLarge!.copyWith(height: 1.20)))), SizedBox(height: 10.v), SizedBox(width: 327.h, child: Text("msg_lorem_ipsum_dolor4".tr, maxLines: 11, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumBluegray500.copyWith(height: 1.40)))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_privacy_policy".tr)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
